name: CI Deploy Dev

on:
  workflow_run:
    workflows: [ 'CI Lint' ]
    branches: [ 'master' ]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./lizaalert_frontend
            docker-compose down
            cd ..
            rm -rf ./lizaalert_frontend
            git clone git@github.com:Studio-Yandex-Practicum/lizaalert_frontend.git
            cd ./lizaalert_frontend
            git checkout enhancement-160-docker-build
            docker-compose build
            docker-compose up -d
