name: CI Deploy Dev

on:
  workflow_run:
    workflows: [ 'CI Lint' ]
    types:
      - completed

jobs:

  build:
    if: ${{github.head_ref == 'master'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/courses-frontend:latest

      - name: Deploy package
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/courses-frontend:latest
            docker stop lizaalert
            docker system prune -f
            docker run --name lizaalert -dit -p 8000:80 --net=host ${{ secrets.DOCKER_USERNAME }}/courses-frontend:latest
